@Biogenom_test_HostAddress = http://localhost:5072
PUT {{Biogenom_test_HostAddress}}/api/users/update/0
Content-Type: application/json
Accept: application/json

{
    "BirthDate": "2000-01-01", 
    "Weight": 70, 
    "Gender": "Male", 
    "Lifestyle": "Moderate"
}
###


GET {{Biogenom_test_HostAddress}}/api/analyze/0
Accept: application/json

###
